# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'jbuilder'
gem 'mysql2'
gem 'puma'
gem 'rails'
gem 'redis'
gem 'ridgepole'

group :development, :test do
  gem 'annotate'
  gem 'bullet'
  gem 'factory_bot_rails', require: false
  gem 'pry-rails'
  gem 'rspec-rails', require: false
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-thread_safety', require: false
  gem 'simplecov', require: false
end
